# Generated by Django 3.1.2 on 2020-10-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('account_broker', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('D', 'Demo'), ('R', 'Real')], max_length=1)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1)),
                ('expiration_date', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
