# Generated by Django 3.1.2 on 2020-10-24 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation_app', '0002_auto_20201024_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlicense',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userlicense',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
